version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: pigrakker
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/mysql

volumes:
  postgres-data:



