version: '3.8'

services:
  app:
    image: pigrakker
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: pigrakker
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
