version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_ROOT_PASSWORD: myrootpassword
      POSTGRES_DB: pigrakker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/mysql

volumes:
  postgres-data:



