stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk
  script:
    - echo "Building the pipeline"
    - cd pigrakker
    - mvn install -B
  artifacts:
    paths:
      - target
test:
  stage: test
  image: maven:latest
  artifacts:
    when: always
    reports:
      junit:
        - target/pigrakker/TEST_*.xml
  script:
    - echo "testing"
    - cd pigrakker
    - mvn verify
  tags:
    - ugrad

deploy:
  stage: deploy
  script:
    - echo "doesn't do anything"
