# Define the stages of your pipeline
stages:
  - build
  - test
  - deploy

# Define global variables
variables:
  # Define variables here, e.g., environment variables, Maven settings, etc.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Define the jobs for each stage
build:
  stage: build
  script:
    - echo "Building the Spring Boot application"
    - mvn clean package -B

test:
  stage: test
  script:
    - echo "Running tests for the Spring Boot application"
    - mvn test -B

deploy:
  stage: deploy
  script:
    - echo "Deploying the Spring Boot application"