name: Build & test App

on:
  push:
    branches:
      - devBranch
      - main
jobs:
  build-test:
    name: build-test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 20

      - name: Unit Tests
        run: mvn -B test --file pigrakker/pom.xml

      - name: Build Application
        run: |
          mvn clean
          mvn -B package --file pigrakker/pom.xml
          
